### ISSUE TITLE
[UI] Tools - Lacking Responsive Support

### ISSUE THREAD

**Issue by Boxofbiscuits97** [LethalModding/LethalModding.com#27]
![image](https://github.com/LethalModding/LethalModding.com/assets/86505354/cd68f359-20b9-48dd-9f4a-a936cc095645)
The package icons do not correctly scale with the containers when changing windows sizes

**Comment by AlbinoGeek** [comment]
```
Note: This happens because the list items are hard-coded to 25% at the moment.
```

**Comment by Nyxchrono** [comment]
https://github.com/LethalModding/LethalModding.com/assets/154691752/65589287-cd15-4681-919a-f8a11133e697

edited the author's original message?!

**Comment by AlbinoGeek** [comment]
As of 7dea3565f5349a24b526f11762e2dddc77c7793c the Tools page now allows for 1-wide, 2-wide, 3-wide and 4-wide layouts using breakpoints. We will re-approach this later with a proper solution.
