### ISSUE TITLE
[UI] All - Accessibility features are not across all web pages

### ISSUE THREAD

**Issue by Boxofbiscuits97** [LethalModding/LethalModding.com#28]
please make my eyes not hurt

Also could the back to main page be in the has mark for them all?
And like not hijack browser history since thas silly.

**Comment by AlbinoGeek** [comment]
Hello!

- Accessibility button is now on all pages (ish?) as of 0dc035c.

- Added consistent breadcrumbs across the whole two pages as of 514a173.

- The `#` symbol is now (in the mean time, while that's the only navigation) a hard-link to `/` as of f1cab92, chances are this will change in the future when there is more than one tool on this page.

- https://nextjs.org/docs/pages/api-reference/functions/use-router#routerback I'll use this (which is functionally equivalent) when that is the case.
